"""Adicionado banco completo

Revision ID: b0dd51fc1f03
Revises: 
Create Date: 2024-12-04 14:33:44.206140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dd51fc1f03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=False),
    sa.Column('ponto_partida', sa.String(length=255), nullable=False),
    sa.Column('destino_principal', sa.String(length=255), nullable=False),
    sa.Column('waypoints', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ponto_turistico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rota_id'], ['rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ponto_turistico')
    op.drop_table('rota')
    op.drop_table('user')
    # ### end Alembic commands ###
